from pydantic import BaseModel, Field
from typing import List, Optional

class Chunk(BaseModel):
    """Represents a chunk of text extracted from a document."""
    text: str = Field(description="The actual text content of the chunk")
    page_number: int = Field(description="The page number where this chunk originated")
    chunk_index: int = Field(description="The sequential index of this chunk within the document")
    token_count: Optional[int] = Field(default=None, description="The estimated token count of the chunk")
    embedding: Optional[List[float]] = Field(default=None, description="The vector representation of the text")

class Document(BaseModel):
    """Represents a parsed document ready for chunking and embedding."""
    document_name: str = Field(description="The name of the file (e.g., HSBC_Annual_Report_2025.pdf)")
    file_path: str = Field(description="The absolute or relative path to the file")
    md5_hash: str = Field(description="MD5 hash of the file for idempotency checks")
    total_pages: int = Field(description="Total number of pages in the document")
    raw_pages_text: List[str] = Field(description="List of text extracted per page, where index = page_number - 1")
    topics: List[str] = Field(default_factory=list, description="List of topics associated with this document for metadata pre-filtering")
    chunks: List[Chunk] = Field(default_factory=list, description="The processed chunks of this document")

class SearchQuery(BaseModel):
    """Encapsulates a semantic search request for the retriever."""
    query_text: str = Field(description="The raw text of the user's query")
    embedding: List[float] = Field(description="The vector representation of the query")
    top_k: int = Field(default=5, description="Maximum number of chunks to retrieve")
    similarity_threshold: float = Field(default=0.5, description="Minimum cosine similarity score [-1, 1]")
    topic_filters: Optional[List[str]] = Field(default=None, description="Optional metadata topics for pre-filtering")

class RetrievedContext(BaseModel):
    """Represents a single chunk of context retrieved from the vector database."""
    doc_id: str = Field(description="The ID of the parent document")
    chunk_id: str = Field(description="The unique ID of this specific chunk")
    text: str = Field(description="The actual text content of the retrieved chunk")
    similarity_score: float = Field(description="The calculated cosine similarity score [-1, 1]")
    metadata: dict = Field(default_factory=dict, description="Additional chunk metadata (e.g., page_number, token_count)")

class RAGResponse(BaseModel):
    """The ultimate structured payload returned by the RAG Agent."""
    query: str = Field(description="The original user query")
    generated_answer: str = Field(description="The final answer synthesized by the LLM")
    retrieved_contexts: List[RetrievedContext] = Field(description="The exact context chunks used to generate the answer, preserved for downstream evaluation")


class QA_Pair(BaseModel):
    """The desired structured format generated by the LLM during Synthetic Data Generation."""
    question: str = Field(description="A highly professional and coherent question derived entirely from the provided text chunk.")
    answer: str = Field(description="The precise, factual, and complete answer to the question, based ONLY on the provided text chunk.")
    complexity: str = Field(description="The difficulty categorization of the question. Must be either 'Factoid' (simple extraction) or 'Reasoning' (requires synthesizing multiple points).")

class GoldenRecord(BaseModel):
    """Represents a single Ground Truth record stored in the database for RAG Evaluation."""
    id: str = Field(description="The unique UUID string for this specific golden test case.")
    batch_name: str = Field(description="Logical grouping/version of the test cases (e.g., 'hsbc_2025_eval_v1').")
    question: str = Field(description="The exact, canonical query string to be fed into the RAG pipeline.")
    ground_truth: str = Field(description="The human-expert or LLM-Teacher verified 'perfect answer' to serve as the benchmark baseline.")
    expected_topics: List[str] = Field(default_factory=list, description="Array of topic names the retrieval SHOULD theoretically hit based on the source chunk.")
    complexity: str = Field(description="Categorization (e.g., 'Factoid', 'Reasoning') for granular metric analysis.")
